BoboTiG/python-mss

- mss/linux.py
__Note:__ do not work on the master branch, only into you own (based on _devel_) or _devel_.
- use errcheck for the validation of the return XRRGetScreenResources, the previous method is deprecated according to ctypes [documentation](https://docs.python.org/2/library/ctypes.html) 
- Fixes #11
> use errcheck instead of deprecated restype with callable, fixes #11

- mss/darwin.py
-  Possible fix for #14 
macOS seems to add extra padding in form of black pixels until the width is divisible by 16, this currently can result in a skewed image.
As a solution the image width is rounded up to the next multiple of 16, so we're taking a bigger screenshot than needed and crop it back to its original size afterwards.
Doing it this way doesn't remove important data in case the padding doesn't happen every time or changes in the future.
- An import for `ceil()` has been added in order to easily round up to the next multiple of 16
- You should still test this on other machines if possible, since all of this was tested on a single macOS device running Sierra 10.12.4
- I didn't test how these changes impact performance, but it should be negligible and it fixes a pretty important …
> Possible fix for BoboTiG/python-mss#14

- CHANGELOG
- tests/conftest.py
Fixed a ResourceWarning:
```python
tests/test_bgra_to_rgb.py::test_good_types
tests/conftest.py:56: ResourceWarning: unclosed file <_io.BufferedReader name='tests/res/monitor-1024x768.raw'>
return open("tests/res/monitor-1024x768.raw", "rb").read()
```
> tests: fix a ResourceWarning: unclosed file

- docs/source/api.rst
Caused overlap with the pixels property
- Change to documentation
> fixes typo in pixel() method

- .travis.yml
- docs/source/examples/callback.py
- docs/source/examples/opencv_numpy.py
- docs/source/examples/pil.py
- docs/source/support.rst
- mss/base.py
- mss/darwin.py
- mss/factory.py
- mss/linux.py
- mss/screenshot.py
- setup.py
- tests/conftest.py
- Test on Python 3.7, requires a small workaround: https://github.com/travis-ci/travis-ci/issues/9815
- Remove testing on 3.7-dev
- Remove already dropped 3.4 from classifiers
- Add python_requires to help pip
> Test on Python 3.7 instead of 3.7-dev

- mss/windows.py
- Fixes #109
- [✓] PEP8 compliant
- [✓] `flake8` passed
> Ignore missing SetProcessDPIAware on WinXP

- mss/windows.py
- Fixes #116 
- changed SetProcessDpiAwareness to correct call on windows 8+ 
Maybe it should be a separate method?
> quick windows dpi bug fix

- .travis.yml
- README.rst
- appveyor.yml
- setup.cfg
- tox.ini
- Exanded the tests matrix: PyPy 3.6, Python 3.5 and 3.6 on macOS.
- Arranged the tests matrix to run macOS tests first as they tend to take way more time.
- Use Python 3.8 for lint, types and docs tox env.
- Added the Python 3.8 classifier.
- Added the AppVeyor badge on the README.
> Tests: Add Python 3.8 to the CI

- CHANGELOG
- mss/tests/test_windows.py
- mss/windows.py
On Windows, the grabbed region is cached to prevent useless resources allocations and speed-up further calls to `.grab()`.
But the check to decide if the cached region needs an update was comparing sizes only. And using same region sizes with different region positions between 2 calls to `.grab()` were resulting in bad screenshots.
> Windows: fix region caching that resulted in bad captures

- CHANGELOG
- mss/tests/test_windows.py
- mss/windows.py
This reverts commit 5e5f3eecc87660b73d11c4c964571f1515c09531.
The patch was indeed a bad idea and fixed nothing ...
I reverted it but kept the test.
> Revert "Windows: fix region caching that resulted in bad captures"

- .gitignore
- CHANGELOG
- MANIFEST.in
- mss/tests/test_setup.py
- setup.cfg
- tox.ini
For instance, the version 5.0.0 shipped a wheel letting users know that Python 2 and 3 are supported.
This is not true for Python 2.
The patch will changes the wheel name: `mss-VERSION-py2.py3-none-any.whl` -> `mss-VERSION-py3-none-any.whl`
> dev: produce wheels for Python 3 only

- CHANGELOG
- CHANGES.rst
- docs/source/api.rst
- mss/base.py
- mss/darwin.py
- mss/factory.py
- mss/linux.py
- mss/tests/test_gnu_linux.py
- mss/tests/test_implementation.py
- mss/windows.py
- `MSSMixin` was really a base class, not a mixin.
- Correctly implemented abstract attributes.
> MSS: renamed again MSSMixin to MSSBase, now derived from abc.ABCMeta

- CHANGELOG
- CHANGES.rst
- CONTRIBUTORS
- mss/tests/test_windows.py
- mss/windows.py
- Fixes #150 
- replace `srcdc` with `srcdc_dict` to maintain srcdc values created by multiple threads
- add a threading lock `MSS._lock` to ensure multi-thread safe
> Windows: fix multi-thread unsafe and update test

- mss/tests/test_windows.py
- mss/windows.py
- setup.cfg
- Fixed the type annotation of `srcdc_dict`.
- Removed obsolete comment in `test_windows.py`.
- Fixed `PytestDeprecationWarning: --no-print-logs is deprecated and scheduled for removal in pytest 6.0.`
- Fixed Sourcery issues in `test_windows.py`.
> Adjustments following previous commit

- mss/windows.py
Fix the type annotation of `srcdc_dict`: `Dict[threading.Thread, int]`
> doc: fix the type annotation of srcdc_dict

- CHANGELOG
- setup.cfg
- Fixes that warning:
```
DeprecationWarning: The "license_file" option is deprecated. Use "license_files" instead.
```
> Fix usage of deprecated "license_file" option

- CHANGELOG
- mss/linux.py
- mss/tests/test_implementation.py
> Linux: the implementation is now thread-safe

- CHANGELOG
- README.rst
- docs/source/installation.rst
Links:
- https://anaconda.org/conda-forge/python-mss
- https://github.com/conda-forge/python-mss-feedstock
- Fixes #170
> The module is now available on conda (closes #170)

- CHANGELOG
- mss/darwin.py
The `int()` builtin function is no more called.
This is a small improvement.
> Mac: reduce the number of function calls

- setup.cfg
UserWarning: Usage of dash-separated 'author-email' will not be supported in future versions. Please use the underscore name 'author_email' instead
UserWarning: Usage of dash-separated 'home-page' will not be supported in future versions. Please use the underscore name 'home_page' instead
UserWarning: Usage of dash-separated 'zip-safe' will not be supported in future versions. Please use the underscore name 'zip_safe' instead
> setup: fix three setuptools warnings

- .github/workflows/tests.yml
- CHANGELOG
- README.rst
- docs/source/api.rst
- docs/source/index.rst
- docs/source/support.rst
- mss/__main__.py
- mss/base.py
- mss/darwin.py
- mss/exception.py
- mss/linux.py
- mss/screenshot.py
- mss/tests/test_gnu_linux.py
- mss/tests/test_issue_220.py
- mss/tools.py
- mss/windows.py
- setup.cfg
> fix(Linux): reset X server error handler on exit to prevent issues with Tk/Tkinter

- MANIFEST.in
Add documentation sources to the list of files included in sdist archives, in order to make it possible to build offline documentation using them.  This is necessary in order to make it possible for Linux distributions such as Gentoo to be able to use sdists.
> Include documentation sources in sdist

- src/mss/linux.py
- src/tests/test_gnu_linux.py
Add an explicit check for the return value of XOpenDisplay().  This function does not seem to use X11 error handlers, and only returns NULL when it fails.  Without an explicit check, mss ended up passing this NULL value to further calls and causing segfaults in libX11.  Now it triggers an explicit exception instead.
- Fixes #246
> linux: Add failure handling to XOpenDisplay() call

- .github/workflows/tests.yml
Use the convenience `xvfb-run` script to start Xvfb on a free DISPLAY and use it to run the test suite.  It is part of the `xvfb` package on Debian.
> dev: run tests via xvfb-run on GitHub Actions

- src/tests/test_gnu_linux.py
- src/tests/test_leaks.py
- tests-requirements.txt
Use the more modern PyVirtualDisplay package instead of xvfbwrapper to run Xvfb.  Most importantly, it uses the more robust approach of starting Xvfb with `-displayfd` and it is actively maintained upstream.  Unfortunately, this does not seem sufficient to entirely eliminate random test failures.
> tests: Use PyVirtualDisplay instead of xvfbwrapper

- setup.cfg
- tests-requirements.txt
Use pytest-rerunfailures plugin to attempt to rerun failing tests up to 5 times.  While this doesn't solve the underlying issue, it should keep the CI green and detecting real issues until we figure out how to solve it properly.
> Use pytest-rerunfailures to rerun failing tests

- CHANGELOG.md
- src/mss/__main__.py
- src/tests/test_implementation.py
That's a very old bug. I guess that means nobody is using the `mss` executable :)
> CLI: fix entry point not taking into account arguments

- docs/source/api.rst
- src/mss/models.py
- src/mss/screenshot.py
ScreenShot.pixels returns a list where each element is a tuple representing a row of pixels. Each of these tuples contain "Pixel"'s. The current model incorrectly hints the return value of ScreenShot.pixels as a list containing "Pixel"s.
- Model for Pixels changed to reflect the true nature of the data
> Pixels model correction

- docs/source/examples/fps_multiprocessing.py
- docs/source/where.rst
- src/mss/linux.py
- src/tests/test_windows.py
- Fixes #
- Fix typos found via `codespell -H`
> docs: fix typos

- docs/source/examples.rst
I was browsing through the docs, and I copy pasted a code snippet from the examples section. It was missing an import statement included in the original example file but not in the docs. I've added all those missing line numbers in the `examples.rst` file.
> docs: include imports statements in examples code snippets

- .github/workflows/tests.yml
- CHANGELOG.md
- README.md
- docs/source/examples/pil_pixels.py
- docs/source/index.rst
- docs/source/support.rst
- pyproject.toml
- src/mss/base.py
- src/mss/screenshot.py
- src/tests/test_implementation.py
It can wait for its official unsupport before unsupporting it here.
> fix: restore Python 3.9 support

- CHANGELOG.md
- CHANGES.md
- src/mss/__init__.py
- src/mss/darwin.py
- src/mss/linux.py
- src/mss/windows.py
- src/tests/conftest.py
- src/tests/test_get_pixels.py
- src/tests/test_implementation.py
- src/tests/test_macos.py
- src/tests/third_party/test_numpy.py
> mac: take screenshots at the nominal resolution
