BoboTiG/python-mss

CONTRIBUTORS, mss/darwin.py, mss/screenshot.py
=> Mac: Properly support all display scaling and resolutions.

.github/PULL_REQUEST_TEMPLATE.md
The dev branch will be deleted after that change.
=> Doc: Remove forcing to use the dev branch

CHANGELOG, CHANGES.rst, LICENSE, docs/source/conf.py, docs/source/where.rst, mss/__init__.py, mss/__main__.py, mss/tools.py, mss/windows.py
Thanks to https://github.com/asweigart/pyautogui/issues/160 for the indirect help, now Windows screen shots are exactly the same as you see it.
=> Windows: Capture all visible windows

tests/test_gnu_linux.py
https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection
https://travis-ci.org/BoboTiG/python-mss/jobs/330759683#L705
=> Use feature detection instead of version detection

CHANGELOG, CHANGES.rst, docs/source/api.rst, docs/source/conf.py, docs/source/examples.rst, docs/source/examples/from_pil_tuple.py, docs/source/examples/part_of_screen.py, docs/source/support.rst, docs/source/usage.rst, docs/source/where.rst, mss/__init__.py, mss/__main__.py, mss/base.py, mss/linux.py, mss/screenshot.py, mss/tools.py, tests/test_tools.py
=> Add PNG compression level control

mss/screenshot.py
- Exposes BGRA data so that we avoid the expensive RGB conversion
=> bgra in Snapshot class

CONTRIBUTORS, mss/windows.py
- Fixes #57 
Apologies on the following items - but I suspect this PR does not make any changes that impact them :)
- [ ✔️ ] PEP8 compliant
- [ ✔️ ] `flake8` passed (bonus)
- [ ✔️ ] `pylint` passed (bonus)
=> [WINDOWS] enable hi-dpi awareness for fullscreen shots. Fixes #57

CHANGELOG, docs/source/conf.py, mss/__init__.py, mss/linux.py
=> Linux: fix a memory leak introduced with 7e8ae57

CHANGELOG, CHANGES.rst, docs/source/api.rst, mss/base.py, mss/darwin.py, mss/exception.py, mss/factory.py, mss/linux.py, mss/windows.py, tests/test_gnu_linux.py
=> MSS: refactor ctypes argtype, restype and errcheck setup

.travis.yml, CHANGELOG, CHANGES.rst, mss/linux.py, tests/test_gnu_linux.py, tox.ini
- Fixes #92 (Linux: fix several XLib functions signature);
- Linux: improve monitors finding by a factor of 44;
- Fix Travis-CI with recent Xvfb failures;
- Removed PyPy from the testing matrix;
- Do not allow any failures in the CI.
=> Linux: fix several XLib functions signature

CHANGELOG, docs/source/examples.rst, docs/source/examples/fps_multiprocessing.py
- Close #82 by providing an example to improve FPS using the `multiprocessing` module.
=> Docs: add an example using the multiprocessing module

mss/windows.py
Original patch by Chris Wheeler (@grintor).
=> Windows: Fix the screen bounding AiO rectangle

CHANGELOG, CHANGES.rst, docs/source/api.rst, docs/source/examples/fps.py, docs/source/usage.rst, mss/darwin.py, mss/linux.py, mss/windows.py, tests/test_leaks.py
=> MSS: better handle resources to prevent leaks

.pre-commit-config.yaml, mss/__main__.py, mss/factory.py, mss/linux.py
Fixes for new errors found by up-to-date mypy and pylint :muscle:
=> Fix new CI failures

.pre-commit-config.yaml, CHANGELOG, tests/test_leaks.py
- Added a regression test for #128
- Added a regression test for #135
=> tests: added regression tests

mss/base.py
Missed remove from 9d01cb0fdfb939ab7b83cf6eb1bce09b27e27dc8.
=> MSS: clean-up MSSBase.monitors

.pre-commit-config.yaml, CHANGELOG
See https://github.com/pre-commit/pre-commit-hooks/issues/344.
=> Fixed flake8 usage in pre-commit

CHANGELOG, setup.cfg, tox.ini
=> tests: fixed a random bug on test_grab_with_tuple_percents()

CHANGELOG, CHANGES.rst, mss/base.py, mss/linux.py, mss/tests/test_gnu_linux.py
=> Linux: better handling of the Xrandr extension (fixes #168)

CHANGELOG, mss/base.py, mss/darwin.py, mss/linux.py, mss/screenshot.py, mss/tests/test_gnu_linux.py, mss/tests/test_macos.py
=> Mac: support macOS Big Sur (fixes #178)

setup.cfg
Pytest --strict option is deprecated #213
=> Fix Pytest deprecated

CHANGELOG, CONTRIBUTORS, docs/source/api.rst, mss/base.py, mss/darwin.py, mss/linux.py, mss/tests/test_gnu_linux.py, mss/windows.py
Original patch by @zorvios on #188.
- Related to #55
- Supersed #188
=> Linux: added mouse support (partially fixes #55)

.github/workflows/tests.yml, .pylintrc, CHANGELOG, CHANGES.rst, check.sh, dev-requirements.txt, docs/source/api.rst, mss/__main__.py, mss/base.py, mss/darwin.py, mss/linux.py, mss/screenshot.py, mss/tests/conftest.py, mss/tests/test_cls_image.py, mss/tests/test_find_monitors.py, mss/tests/test_get_pixels.py, mss/tests/test_gnu_linux.py, mss/tests/test_implementation.py, mss/tests/test_leaks.py, mss/tests/test_save.py, mss/tests/test_third_party.py, mss/tests/test_tools.py, mss/tools.py, mss/windows.py, setup.cfg
=> linux: several fixes, and tests

mss/linux.py
- Fixes #220 by letting the ```MSS.close()``` restore the previous error handler
- The current implementation resets the error handler to a dummy function, but this PR restores the previous handler backed up at the ```MSS.__init()```.
=> Fix issue #220 by letting close() restore the previous error handler.

CHANGELOG.md, src/mss/windows.py, src/tests/test_windows.py
=> Windows: refactored how internal handles are stored
